CREATE TABLE PgLogRows (
PgLogRowID integer not null default nextval('seqPgLogRows'),
LogTime timestamp(3) with time zone,
UserName text,
DatabaseName text,
ProcessID integer,
ConnectionFrom text,
SessionID text,
SessionLineNum bigint,
CommandTag text,
SessionStartTime timestamp with time zone,
VirtualTransactionID text,
TransactionID bigint,
ErrorSeverity text,
SqlStateCode text,
Message text,
Detail text,
Hint text,
InternalQuery text,
InternalQueryPos integer,
Context text,
Query text,
QueryPos integer,
Location text,
Filename text,
PgLogPatternID integer,
PgLogFileID integer not null,
ApplicationName text,
PRIMARY KEY (PgLogRowID),
UNIQUE (SessionID, SessionLineNum),
FOREIGN KEY (PgLogPatternID) REFERENCES PgLogPatterns(PgLogPatternID),
FOREIGN KEY (PgLogFileID) REFERENCES PgLogFiles(PgLogFileID)
);
